apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: ClusterIP
  ports:
    -
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: helloworld
          image: kennyoctotest/cf-runtime-pipelines:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
